name: app_catalogo
description: App catalogo
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  equatable: ^2.0.3
  connectivity_plus: ^2.3.6
  get_storage: ^2.0.3
  iconsax: ^0.0.8
  flow_builder: ^0.0.9
  http: ^0.13.4
  oxidized: ^5.2.0
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.1

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/catalog.jpeg"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/thumbnails_black.png
    - assets/icons/arrow_right.svg
    - assets/icons/search.svg
    - assets/icons/notification.svg
    - assets/icons/arrow_left.svg
    - assets/icons/specifications.svg
    - assets/icons/colors.svg

  fonts:
    - family: BwNista
      fonts:
        - asset: assets/font/BwNistaGrotesk-Regular.ttf
        - asset: assets/font/BwNistaGrotesk-Black.ttf
          weight: 900
        - asset: assets/font/BwNistaGrotesk-Bold.ttf
          weight: 700
        - asset: assets/font/BwNistaGrotesk-Medium.ttf
          weight: 600
